# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# wh2+Y you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: GOGOGO Store
email: your-email@example.com
description: Loja Online de Roupa Masculina. Compre em Portugal Continental e Ilhas T-shirts, Camisas, Polos, Casacos e muito mais. Portes grátis para compras superiores a 40€. Encontre a roupa da moda que procura! 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.gogogostore.pt" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  

# Build settings
permalink: pretty
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  
collections:
  products:
    output: true
  blog:
    output: true

future: true
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
plugins:
  - jekyll-seo-tag