---
label: Product Page
hide_body: true
fields:
- type: text
  name: layout
  label: layout
- type: number
  name: id
  label: id
- type: text
  name: name
  label: name
- type: text
  name: link
  label: link
- type: number
  name: price
  label: price
- type: number
  name: weight
  label: weight
- type: file
  name: image
  label: image
- type: file
  name: sec
  label: sec
- type: file
  name: thir
  label: thir
- type: text
  name: att
  label: att
- type: text
  name: categoria
  label: categoria
- type: list
  name: color
  label: color
- type: text
  name: discrip
  label: discrip
- type: boolean
  name: novo
  label: novo
- type: boolean
  name: maisvendidos
  label: maisvendidos
- type: text
  name: stock
  label: stock
