---
label: Product Page
hide_body: false
display_field: name
fields:
- type: text
  name: layout
  label: layout
  hidden: false
  default: product
- type: number
  name: id
  label: Product ID
  config:
    required: true
- type: text
  name: name
  label: Product Name
  config:
    required: true
- type: text
  name: link
  label: Slug
  config:
    required: true
- type: number
  name: price
  label: Price
  config:
    required: true
- name: newprice
  type: text
  config:
    required: false
  label: Old Price
- type: number
  name: weight
  label: Weight
  config:
    required: true
- type: file
  name: image
  label: Display Image
- type: file
  name: sec
  label: Second Image
- type: file
  name: thir
  label: Third Image
- name: four
  type: file
  config:
    maxSize: 250
  label: Fourth Image
- type: text
  name: categoria
  label: Category
- type: text
  name: att
  label: Sub-category
- type: list
  name: color
  config:
    use_select: false
    source:
      type: simple
      section: ''
      path: ''
  label: Colores Variations
- type: text
  name: discrip
  label: Search Tags
  description: 'Seperate by spaces (ex: black white rose)'
- type: boolean
  name: novo
  label: Is it new?
- type: boolean
  name: maisvendidos
  label: Is it a best seller?
- type: text
  name: stock
  config:
    required: true
  label: Do you have stock?
  description: Input "sim" or "nao".
- name: new
  type: boolean
  label: Novidade
- name: inicial
  type: boolean
  label: inicial
- name: inicialhat
  type: boolean
  label: inicialhat
- name: discription
  type: text
  config:
    required: false
  label: discription
pages:
- _products/sweats/padrao/sweatmsshades.md
- _products/sweats/padrao/sweatmsrow.md
- _products/sweats/padrao/sweatclassicstreet.md
- _products/sweats/padrao/sweatmsbasic.md
- _products/sweats/padrao/sweatmstrina.md
- _products/sweats/padrao/sweatsurfstreet.md
- _products/sweats/padrao/sweatsleakstripes.md
- _products/sweats/padrao/sweatmssharknation.md
- _products/sweats/padrao/sweatmsreactor.md
- _products/sweats/padrao/sweatmsbadnews.md
- _products/sweats/padrao/sweatwoodtexture.md
- _products/sweats/padrao/sweatbreak.md
- sweatmsreact.md
- _products/sweats/padrao/sweatmoodclassic.md
- _products/acessorios/colares/colaranchorcross.md
- _products/acessorios/colares/colarfancyanchor.md
- _products/acessorios/colares/colarblingcross.md
- _products/acessorios/colares/colarskulljewel.md
- _products/acessorios/colares/colarcrosspin.md
- _products/fatosdetreino/fatodetreinoshadow.md
- _products/fatosdetreino/fatodetreinopro.md
- _products/fatosdetreino/fatodetreinoretro.md
- _products/fatosdetreino/fatodetreinodot.md
- _products/fatosdetreino/fatodetreinodragondeluxe.md
- _products/sweats/padrao/sweatimpired.md
- _products/sweats/padrao/sweatsquadseven.md
- _products/sweats/padrao/sweatthreesimplerules.md
- _products/sweats/padrao/sweatnewyork.md
- _products/casacos/padrao/casacomixer.md
- _products/casacos/padrao/casaconasaspecial.md
- _products/casacos/padrao/casacorobinred.md
- _products/casacos/padrao/sweatfutureio.md
- _products/tshirts/padrao/tshirtmsstreetblue.md
- _products/casacos/padrao/casaconasaburgler.md
- _products/casacos/padrao/casacoburglar.md
- _products/sweats/padrao/sweatdextar.md
- _products/sweats/padrao/sweatnewtaxi.md
- _products/polos/padrao/polomsnr30.md
- _products/tshirts/padrao/tshirtmscaptainblue.md
- _products/sweats/padrao/sweatnycbelongs.md
- _products/tshirts/padrao/tshirtmsfrenchstyle.md
- _products/sweats/padrao/sweatnychandsome.md
- _products/sweats/padrao/sweatsportorange.md
- _products/tshirts/padrao/tshirtmsblackmatte.md
- _products/sweats/padrao/sweatallstar.md
- _products/casacos/padrao/casacodanceblue.md
- _products/bonesecaps/basic/capmsbluebasic.md
- _products/bonesecaps/basic/capmswhitebasic.md
- _products/bonesecaps/basic/chapeumsblackbasic.md
- _products/polos/padrao/polomspartywhite.md
- _products/polos/padrao/tshirtmstropicalwhite.md
- _products/polos/padrao/polomsparty.md
- _products/polos/padrao/polomscollar.md
- _products/polos/padrao/polomstropical.md
- _products/polos/padrao/polomscollarblack.md
- _products/polos/padrao/polomsfrenchstyle.md
- _products/tshirts/basic/tshirtmsred.md
- _products/tshirts/basic/thsirtmsredfur.markdown
- _products/tshirts/basic/thsirtmsnavyfur.markdown
- _products/tshirts/basic/thsirtmsbrownfur.markdown
- _products/tshirts/basic/thsirtmsblack.markdown
- _products/tshirts/basic/tshirtmstricolor.md
- _products/tshirts/basic/tshirtmscyan.md
- _products/tshirts/basic/tshirtmsrubystraight.markdown
- _products/tshirts/basic/tshirtmsblue.md
- _products/tshirts/basic/thsirtmsbluestraight.markdown
- _products/tshirts/basic/thsirtmsbluefur.markdown
- _products/tshirts/basic/thsirtmsredstraight.markdown
- _products/tshirts/basic/tshirtmstapesgreen.md
- _products/tshirts/basic/tshirtmsbrown.md
- _products/tshirts/basic/thsirtmsbrownstraight.markdown
- _products/tshirts/basic/tshirtmsorange.md
- _products/tshirts/basic/tshirtmsblack.md
- _products/tshirts/basic/thsirtmsbearfur.markdown
- _products/tshirts/basic/thsirtmsskystraight.markdown
- _products/tshirts/basic/tshirtmstapes.md
- _products/tshirts/basic/tshirtmsgreen.md
- _products/tshirts/basic/thsirtmsbasicbrown.markdown
- _products/tshirts/padrao/tshirtmscaptainblack.md
- _products/tshirts/padrao/tshirtmsallstar.md
- _products/tshirts/padrao/tshirtmsgoldromewhite.md
- _products/tshirts/padrao/tshirtmsspecial7sportred.md
- _products/tshirts/padrao/tshirtmsfullgoldarmorwhite.md
- _products/tshirts/padrao/tshirtmsbarslinegrey.md
- _products/tshirts/padrao/tshirtmsshoulderroseblack.md
- _products/tshirts/padrao/tshirtmshalfblackmatte.md
- _products/tshirts/padrao/tshirtmscrystalmotion.md
- _products/tshirts/padrao/tshirtmshalfwhitematte.md
- _products/tshirts/padrao/tshirtmsspecial7.md
- _products/tshirts/padrao/tshirtmspixel.md
- _products/tshirts/padrao/tshirtmsspecial7sportblack.md
- _products/tshirts/padrao/tshirtmsitalianstyle.md
- _products/tshirts/padrao/tshirtmsarmorroseblack.md
- _products/tshirts/padrao/tshirtmsarmorrose.md
- _products/tshirts/padrao/tshirtmsfocus.md
- _products/tshirts/padrao/tshirtmscastlerose.md
- _products/tshirts/padrao/tshirtmsargentina.md
- _products/tshirts/padrao/tshirtmstricolorred.md
- _products/tshirts/padrao/tshirtmsgoldflakeblack.md
- _products/tshirts/padrao/tshirtmsgoldluckblack.md
- _products/tshirts/padrao/tshirtmscaptain.md
- _products/tshirts/padrao/tshirtmstricolorwhite.md
- _products/tshirts/padrao/tshirtmslightbluebaltic.md
- _products/tshirts/padrao/tshirtgreekred.md
- _products/tshirts/padrao/tshirtmsfocusblack.md
- _products/tshirts/padrao/tshirtmsallstarred.md
- _products/tshirts/padrao/tshirtmsfrenchstyleyellow.md
- _products/tshirts/padrao/thsirtmsrosestripe.markdown
- _products/tshirts/padrao/tshirtmseagle.md
- _products/tshirts/padrao/tshirtmsbarsline.md
- _products/tshirts/padrao/tshirtmsvicecity.md
- _products/tshirts/padrao/tshirtmsbaltic.md
- _products/tshirts/padrao/tshirtmsrelaxbarsgray.md
- _products/tshirts/padrao/tshirtmsplayer.md
- _products/tshirts/padrao/tshirtmyellowsbaltic.md
- _products/tshirts/padrao/thsirtmsdegrade.markdown
- _products/tshirts/padrao/thsirtmsgoldflames.markdown
- _products/tshirts/padrao/tshirtmsspecial7sportwhite.md
- _products/tshirts/padrao/tshirtmsitalianstyleblack.md
- _products/tshirts/padrao/tshirtmsshoulderrose.md
- _products/tshirts/padrao/tshirtmsfrenchblue.md
- _products/tshirts/padrao/tshirtmsaquamotion.md
- _products/tshirts/padrao/tshirtmsfrenchstylered.md
- _products/tshirts/padrao/thsirtmsgoldflake.markdown
- _products/tshirts/padrao/tshirtmsfocusyellow.md
- _products/tshirts/padrao/tshirtmspinkbaltic.md
- _products/tshirts/padrao/tshirtmstapesblack.md
- _products/tshirts/padrao/thsirtmsgoldluck.markdown
- _products/camisas/padrao/camisastripeswhite.md
- _products/camisas/padrao/camisamsstripes.markdown
- _products/camisas/padrao/camisamsstripesclassicdark.markdown
- _products/bonesecaps/basic/chapeumsgraybasic.md
- _products/bonesecaps/basic/bonemsorangebasic.md
- _products/bonesecaps/basic/capmsblackandyellowbasic.md
- _products/bonesecaps/basic/bonemstroopdark.md
- _products/bonesecaps/basic/capmsblackandwhite.md
- _products/bonesecaps/basic/chapeumsblackyellowbasic.md
- _products/bonesecaps/basic/bonemsbrownbasic.md
- _products/bonesecaps/basic/bonemsredbasic.md
- _products/bonesecaps/basic/capmsblueandred.md
- _products/bonesecaps/basic/bonemsgreenbasic.md
- _products/bonesecaps/basic/bonemstrooplight.md
- _products/bonesecaps/basic/bonemsbluebasic.md
- _products/bonesecaps/basic/capmsblackbasic.md
- _products/bonesecaps/basic/bonemsbasicpurple.md
- _products/bonesecaps/basic/capmsredbasic.md
- _products/bonesecaps/basic/bonemsyellowbasic.md
- _products/calcoes/basic/calcoesmsbluebeach.md
- _products/calcoes/basic/calcoesbluebasic.md
- _products/calcoes/basic/calcoesmsstripegray.md
- _products/calcoes/basic/calcoesmsstripeblack.md
- _products/calcoes/basic/calcoesmscaptaingray.md
- _products/calcoes/basic/calcoesmssportbranco.md
- _products/calcoes/basic/calcoesmscaptainblack.md
- _products/casacos/basic/casacomsbikerbasic.md
- _products/casacos/basic/casacomsfullwinter.md
- _products/casacos/padrao/casacomsjungle.markdown
- _products/casacos/padrao/casacomsurbanred.markdown
- _products/casacos/padrao/casacomsurbanyellow.markdown
- _products/casacos/padrao/casacomsrainblue.markdown
- _products/casacos/padrao/casacomsrain.markdown
- _products/casacos/padrao/casacomsurbanblue.md
- _products/tshirts/basic/tshirtmsbalticbasic.md
- _products/tshirts/basic/tshirtmsbacklinesred.md
- _products/tshirts/basic/tshirtmsbacklinesblack.md
- _products/tshirts/basic/tshirtmsbacklines.md
- _products/tshirts/basic/tshirtmsrosestripewhite.md
- _products/tshirts/basic/tshirtmscrystalmotionorange.md
- _products/tshirts/basic/tshirtmsyellow.md
